spring:
  application:
    name: deposit-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    enabled:  false
#    change-log: classpath:/db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
  paths-to-match: /**
#axon:
#  axonserver:
#    enabled: false

axon:
  axonserver:
    enabled: false               # use local EventBus, not Axon Server
  eventhandling:
    processors:
      deposit-projections:       # must match @ProcessingGroup("deposit-projections")
        mode: subscribing
        source: eventBus
        #        mode: tracking # <--- projector runs inline with command handling
#        mode: tracking
#        source: eventStore
        # optional: start at tail (to read past events)
#        initial-segment-count: 1
#  eventstore:
#    jdbc:
#      schema: default

camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      grpc-address: http://192.168.179.20:26500
      rest-address: http://192.168.179.20:8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: WARN
    org.axonframework: DEBUG
    org.hibernate.type.descriptor.sql: TRACE